"""
Self-Critique Adaptive Retrieval Agent
=======================================
Implements Approach B: Re-retrieve + Re-generate.

After the initial RAG answer, a Critic LLM evaluates:
  1. Is the answer grounded in the retrieved context?
  2. Does the answer fully address the question?
  3. Confidence score (0.0 – 1.0)

If confidence < 0.7, the critic suggests a reformulated query.
The agent re-retrieves from Qdrant with the new query,
re-ranks, re-generates, and critiques again (max 2 retries).
"""

import json
import time
from typing import Optional

from groq import Groq
from app.config import settings
from app.retrieval.vector_store import search_hybrid, ensure_collection_exists, detect_document_from_query
from app.retrieval.reranker import rerank
from app.generation.llm import generate_grounded_answer, get_groq_client


CRITIQUE_PROMPT = """\
You are a strict quality-assurance critic for a Retrieval-Augmented Generation (RAG) system.

Given:
- The user's QUESTION
- The CONTEXT chunks retrieved from a technical document database
- The ANSWER generated by the RAG system

Evaluate the answer on two dimensions:
1. **Grounded**: Is every claim in the answer supported by the provided context? (no hallucination)
2. **Complete**: Does the answer fully address all parts of the question using the available context?

Respond ONLY with a valid JSON object (no markdown, no explanation outside the JSON):
{{
  "is_grounded": true/false,
  "is_complete": true/false,
  "confidence": <float between 0.0 and 1.0>,
  "reasoning": "<brief explanation of your assessment>",
  "suggested_query": "<a reformulated search query that would retrieve better evidence, or empty string if answer is satisfactory>"
}}

QUESTION: {question}

CONTEXT:
{context}

ANSWER: {answer}
"""

CONFIDENCE_THRESHOLD = 0.7
MAX_RETRIES = 2


def critique_answer(question: str, answer: str, context_texts: list[str]) -> dict:
    """
    Sends the question + answer + contexts to Groq LLM critic.
    Returns a dict with is_grounded, is_complete, confidence, reasoning, suggested_query.
    """
    client = get_groq_client()

    context_str = "\n\n".join(
        f"[Chunk {i+1}]: {text}" for i, text in enumerate(context_texts)
    )

    prompt = CRITIQUE_PROMPT.format(
        question=question,
        context=context_str,
        answer=answer,
    )

    try:
        response = client.chat.completions.create(
            model="qwen/qwen3.8-27b",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            reasoning_effort="none",
            max_completion_tokens=512,
        )

        raw_text = response.choices[0].message.content.strip()

        # Parse JSON from the response (handle potential markdown wrapping)
        json_text = raw_text
        if "```json" in json_text:
            json_text = json_text.split("```json")[1].split("```")[0].strip()
        elif "```" in json_text:
            json_text = json_text.split("```")[1].split("```")[0].strip()

        result = json.loads(json_text)

        return {
            "is_grounded": result.get("is_grounded", True),
            "is_complete": result.get("is_complete", True),
            "confidence": float(result.get("confidence", 1.0)),
            "reasoning": result.get("reasoning", ""),
            "suggested_query": result.get("suggested_query", ""),
        }

    except (json.JSONDecodeError, Exception) as e:
        # If critique parsing fails, assume answer is acceptable (fail-open)
        return {
            "is_grounded": True,
            "is_complete": True,
            "confidence": 0.8,
            "reasoning": f"Critique parsing failed ({str(e)[:80]}), defaulting to accept.",
            "suggested_query": "",
        }


def agentic_rag_pipeline(
    query: str,
    top_k: int = 5,
    exclude_images: bool = False,
    doc_name: Optional[str] = None,
    session_id: Optional[str] = None,
    max_retries: int = MAX_RETRIES,
) -> dict:
    """
    Self-Critique Adaptive Retrieval Agent pipeline.

    Flow:
      1. Standard RAG: hybrid search → rerank → generate
      2. Critic evaluates answer quality
      3. If confidence < threshold: reformulate query → re-retrieve → re-rank → re-generate
      4. Repeat up to max_retries times
      5. Return final answer + full critique_log

    Returns:
        dict with keys: answer, sources, critique_log, attempts, final_query
    """
    ensure_collection_exists()

    # Resolve document routing
    active_doc_name = doc_name or detect_document_from_query(query)

    critique_log = []
    current_query = query
    final_answer = None
    final_sources = None
    attempts = 0

    for attempt in range(1 + max_retries):
        attempts = attempt + 1
        attempt_start = time.time()

        # Step 1: Hybrid search
        retrieve_k = max(top_k * 3, 30)
        hybrid_points = search_hybrid(
            query=current_query,
            top_k=retrieve_k,
            exclude_images=exclude_images,
            doc_name=active_doc_name,
            session_id=session_id,
        )

        if not hybrid_points:
            critique_log.append({
                "attempt": attempts,
                "query_used": current_query,
                "result": "no_chunks_found",
                "confidence": 0.0,
                "reasoning": "No relevant chunks found in vector store.",
                "duration_ms": int((time.time() - attempt_start) * 1000),
            })
            break

        # Step 2: Rerank
        candidate_dicts = [
            dict(p.payload, hybrid_score=p.score) for p in hybrid_points
        ]
        reranked_chunks = rerank(
            query=current_query,
            candidates=candidate_dicts,
            top_k=top_k,
        )

        # Step 3: Generate grounded answer
        grounded_result = generate_grounded_answer(
            question=query,  # Always use original question for generation
            chunks=reranked_chunks,
        )

        answer_text = grounded_result["answer"]
        context_texts = [c.get("text", "") for c in reranked_chunks]

        # Step 4: Critique the answer
        critique = critique_answer(
            question=query,  # Always critique against original question
            answer=answer_text,
            context_texts=context_texts,
        )

        attempt_log = {
            "attempt": attempts,
            "query_used": current_query,
            "confidence": critique["confidence"],
            "is_grounded": critique["is_grounded"],
            "is_complete": critique["is_complete"],
            "reasoning": critique["reasoning"],
            "suggested_query": critique.get("suggested_query", ""),
            "duration_ms": int((time.time() - attempt_start) * 1000),
        }
        critique_log.append(attempt_log)

        final_answer = answer_text
        final_sources = reranked_chunks

        # Step 5: Check if answer passes critique
        if critique["confidence"] >= CONFIDENCE_THRESHOLD and critique["is_grounded"]:
            break  # Answer is good enough

        # Step 6: If critique fails and we have retries left, reformulate query
        if attempt < max_retries:
            suggested = critique.get("suggested_query", "").strip()
            if suggested and suggested != current_query:
                current_query = suggested
            else:
                # If no suggestion or same query, try combining original + reasoning
                current_query = f"{query} {critique.get('reasoning', '')[:50]}"

    return {
        "answer": final_answer or "No relevant information found in the document index.",
        "sources": final_sources or [],
        "critique_log": critique_log,
        "attempts": attempts,
        "final_query": current_query,
    }
